use super::{SchemaDeclaration as D, SchemaKind as K};

const RBAC_E2E: &str = "tests/rbac_e2e.rs";
const GRAPH_E2E: &str = "tests/edges_db_verified_e2e.rs";
const REASONING_E2E: &str = "tests/reasoning_extraction_e2e.rs";
const RESERVED_MILESTONE: &str = "#157 architecture decision before v0.18.0";

pub const EDGES: &[D] = &[
    D::active(
        K::Edge,
        "RBAC_MEMBER_OF",
        "core/rbac",
        "RbacManager::grant",
        "RbacManager::snapshot",
        RBAC_E2E,
        "Principal membership and group role.",
        "rbac_member_of_count",
    ),
    D::active(
        K::Edge,
        "MEMORY_IN_RBAC_GROUP",
        "core/rbac",
        "RbacManager::assign_memory_to_group",
        "RbacManager::authorize",
        RBAC_E2E,
        "Materialized memory visibility boundary.",
        "memory_in_rbac_group_count",
    ),
    D::active(
        K::Edge,
        "RBAC_GROUP_IN_DEDUP_GROUP",
        "core/rbac",
        "RbacManager::attach_group_to_dedup_as",
        "RbacManager::snapshot",
        RBAC_E2E,
        "Workspace membership in a dedup federation.",
        "rbac_group_in_dedup_group_count",
    ),
    D::active(
        K::Edge,
        "MEMORY_IN_RBAC_DEDUP_GROUP",
        "core/rbac",
        "RbacManager::assign_memory_to_dedup",
        "RbacManager::memory_scope",
        RBAC_E2E,
        "Persisted dedup-federation provenance.",
        "memory_in_rbac_dedup_group_count",
    ),
    D::active(
        K::Edge,
        "HAS_MEMORY",
        "tooling_manager/add_pipeline",
        "add_pipeline::cross_user",
        "search_memory scope projection",
        "tests/hive_memory_e2e.rs",
        "Authorship and holder stance; not an ACL.",
        "has_memory_count",
    ),
    D::active(
        K::Edge,
        "INSTANCE_OF",
        "mind_toolbox/ontology",
        "OntologyManager::map_memory_to_concepts",
        "search_by_concept",
        "tests/ontology_classification_e2e.rs",
        "Memory classification in the fixed ontology.",
        "instance_of_count",
    ),
    D::active(
        K::Edge,
        "MENTIONS",
        "mind_toolbox/entity",
        "add_pipeline::entity_links",
        "getMemoryGraphStats",
        GRAPH_E2E,
        "Salient entity mention.",
        "mentions_count",
    ),
    D::active(
        K::Edge,
        "EXTRACTED_ENTITY",
        "mind_toolbox/entity",
        "add_pipeline::entity_links",
        "getMemoryGraphStats",
        GRAPH_E2E,
        "Entity extraction provenance.",
        "extracted_entity_count",
    ),
    D::reserved(
        K::Edge,
        "IS_A",
        "mind_toolbox/ontology",
        RESERVED_MILESTONE,
        "Reserved concept-to-concept representation; memory-level IS_A is live in MEMORY_RELATION.",
        "is_a_count",
    ),
    D::active(
        K::Edge,
        "HAS_SUBTYPE",
        "mind_toolbox/ontology",
        "OntologyManager::load",
        "OntologyManager::load",
        "tests/ontology_classification_e2e.rs",
        "Fixed ontology hierarchy.",
        "has_subtype_count",
    ),
    D::active(
        K::Edge,
        "RELATES_TO",
        "mind_toolbox/entity",
        "add_pipeline::entity_links",
        "getEntityRelations",
        GRAPH_E2E,
        "Typed relation between extracted entities.",
        "relates_to_count",
    ),
    D::reserved(
        K::Edge,
        "PART_OF",
        "mind_toolbox/entity",
        RESERVED_MILESTONE,
        "Reserved entity-composition edge; memory-level PART_OF is live in MEMORY_RELATION.",
        "part_of_count",
    ),
    D::active(
        K::Edge,
        "VALID_IN",
        "tooling_manager/add_pipeline",
        "add_pipeline::context_link",
        "getMemoryContexts",
        GRAPH_E2E,
        "Contextual validity of a memory.",
        "valid_in_count",
    ),
    D::reserved(
        K::Edge,
        "CREATED_IN",
        "core/session",
        RESERVED_MILESTONE,
        "Reserved Memory-to-Session provenance; Session has no live producer.",
        "created_in_count",
    ),
    D::active(
        K::Edge,
        "AGENT_CREATED",
        "tooling_manager/add_pipeline",
        "ToolingManager::link_agent_to_memory",
        "getMemoryAgent",
        "tests/swarm_e2e.rs",
        "Agent execution provenance for a memory write.",
        "agent_created_count",
    ),
    D::active(
        K::Edge,
        "HAS_HISTORY",
        "tooling_manager/add_pipeline",
        "ToolingManager::add_memory_history_event",
        "getMemoryHistory",
        "tests/supersede_demotion_e2e.rs",
        "Memory decision audit trail.",
        "has_history_count",
    ),
    D::active(
        K::Edge,
        "HAS_CHUNK",
        "mind_toolbox/chunking",
        "ChunkingManager::store_chunks",
        "getMemoryChunks",
        "tests/chunking_e2e.rs",
        "Memory-to-reconstruction-chunk order.",
        "has_chunk_count",
    ),
    D::active(
        K::Edge,
        "MEMORY_RELATION",
        "mind_toolbox/reasoning",
        "ReasoningEngine::store_relation",
        "ReasoningEngine::get_chain",
        REASONING_E2E,
        "Typed SUPPORTS, RELATES_TO, PART_OF and IS_A memory semantics.",
        "memory_relation_count",
    ),
    D::active(
        K::Edge,
        "IMPLIES",
        "mind_toolbox/reasoning",
        "ReasoningEngine::store_relation",
        "ReasoningEngine::get_chain",
        REASONING_E2E,
        "First-class logical implication.",
        "implies_count",
    ),
    D::active(
        K::Edge,
        "BECAUSE",
        "mind_toolbox/reasoning",
        "ReasoningEngine::store_relation",
        "ReasoningEngine::get_chain",
        REASONING_E2E,
        "First-class causal justification.",
        "because_count",
    ),
    D::active(
        K::Edge,
        "CONTRADICTS",
        "tooling_manager/contradictions",
        "ReasoningEngine::store_relation",
        "ToolingManager::resolve_contradiction",
        "tests/contradiction_debt_e2e.rs",
        "First-class contradiction and resolution state.",
        "contradicts_count",
    ),
    D::active(
        K::Edge,
        "SUPERSEDES",
        "tooling_manager/add_pipeline",
        "add_pipeline::decide",
        "getSupersedingMemory",
        "tests/supersede_demotion_e2e.rs",
        "Append-only replacement history.",
        "supersedes_count",
    ),
    D::active(
        K::Edge,
        "HAS_EMBEDDING",
        "mind_toolbox/memory",
        "addMemoryEmbedding",
        "smartVectorSearch",
        "tests/read_path_e2e.rs",
        "Memory-to-primary-vector projection.",
        "has_embedding_count",
    ),
    D::reserved(
        K::Edge,
        "ENTITY_HAS_EMBEDDING",
        "mind_toolbox/entity",
        RESERVED_MILESTONE,
        "Reserved entity-vector projection; no Rust producer persists EntityEmbedding.",
        "entity_has_embedding_count",
    ),
    D::reserved(
        K::Edge,
        "CHUNK_TO_EMBEDDING",
        "reserved/document-ingest",
        RESERVED_MILESTONE,
        "Reserved DocChunk vector projection; MemoryChunk is deliberately not embedded.",
        "chunk_to_embedding_count",
    ),
    D::reserved(
        K::Edge,
        "CONCEPT_RELATED_TO",
        "mind_toolbox/ontology",
        RESERVED_MILESTONE,
        "Reserved horizontal concept relation in the fixed ontology.",
        "concept_related_to_count",
    ),
    D::active(
        K::Edge,
        "SUBCATEGORY_OF",
        "agents/clotho",
        "ToolingManager::link_subcategory",
        "category graph projection",
        "tests/clotho_autotag_e2e.rs",
        "Controlled-vocabulary hierarchy.",
        "subcategory_of_count",
    ),
    D::active(
        K::Edge,
        "ALIAS_OF",
        "agents/clotho",
        "Clotho::alias_pass",
        "Clotho category convergence",
        "tests/clotho_alias_e2e.rs",
        "Canonical category synonym relation.",
        "alias_of_count",
    ),
    D::active(
        K::Edge,
        "TAGGED_AS",
        "agents/clotho",
        "ToolingManager::tag_memory",
        "Lachesis category routing",
        "tests/clotho_autotag_e2e.rs",
        "Memory membership in controlled categories.",
        "tagged_as_count",
    ),
    D::active(
        K::Edge,
        "MOIRAI_DERIVED_FROM",
        "core/rbac_moirai",
        "RbacManager::reify_moirai_provenance",
        "control_plane::load_moirai",
        "tests/rbac_bootstrap_e2e.rs",
        "Admin-only hypothesis provenance.",
        "moirai_derived_from_count",
    ),
];
