use super::{SchemaDeclaration as D, SchemaKind as K};

const RBAC_E2E: &str = "tests/rbac_e2e.rs";
const MEMORY_E2E: &str = "tests/mcp_write_e2e.rs";
const GRAPH_E2E: &str = "tests/edges_db_verified_e2e.rs";
const MOIRAI_E2E: &str = "tests/clotho_autotag_e2e.rs";
const BUFFER_E2E: &str = "tests/ingest_buffer_e2e.rs";
const RESERVED_MILESTONE: &str = "#157 architecture decision before v0.18.0";

pub const NODES: &[D] = &[
    D::active(
        K::Node,
        "User",
        "core/rbac",
        "schema::ensureUser",
        "RbacManager::principal_registry",
        RBAC_E2E,
        "Principal registry and memory authorship anchor.",
        "user_count",
    ),
    D::active(
        K::Node,
        "RbacGroup",
        "core/rbac",
        "RbacManager::create_group_as",
        "RbacManager::snapshot",
        RBAC_E2E,
        "Concrete access workspace.",
        "rbac_group_count",
    ),
    D::active(
        K::Node,
        "RbacDedupGroup",
        "core/rbac",
        "RbacManager::create_dedup_group_as",
        "RbacManager::snapshot",
        RBAC_E2E,
        "Optional cross-workspace dedup federation.",
        "rbac_dedup_group_count",
    ),
    D::active(
        K::Node,
        "RbacAssignment",
        "core/rbac",
        "RbacManager::grant",
        "RbacManager::snapshot",
        RBAC_E2E,
        "Auditable global and group role grant.",
        "rbac_assignment_count",
    ),
    D::active(
        K::Node,
        "RbacConfig",
        "core/rbac",
        "RbacManager::bootstrap_compatibility",
        "RbacManager::snapshot",
        RBAC_E2E,
        "Permanent RBAC bootstrap and policy revision.",
        "rbac_config_count",
    ),
    D::reserved(
        K::Node,
        "Session",
        "core/session",
        RESERVED_MILESTONE,
        "Reserved interaction-session shape; Helixir is not a chat log.",
        "session_count",
    ),
    D::active(
        K::Node,
        "Agent",
        "tooling_manager/swarm",
        "ToolingManager::agent_heartbeat",
        "ToolingManager::swarm_status",
        "tests/swarm_e2e.rs",
        "Execution-instance presence and agent provenance.",
        "agent_count",
    ),
    D::active(
        K::Node,
        "Memory",
        "tooling_manager/add_pipeline",
        "ToolingManager::add_memory",
        "SearchEngine::search",
        MEMORY_E2E,
        "Atomic long-term knowledge record.",
        "memory_count",
    ),
    D::active(
        K::Node,
        "Entity",
        "tooling_manager/add_pipeline",
        "add_pipeline::entity_links",
        "getMemoryGraphStats",
        GRAPH_E2E,
        "Extracted and deduplicated named entity.",
        "entity_count",
    ),
    D::active(
        K::Node,
        "Concept",
        "mind_toolbox/ontology",
        "OntologyManager::load",
        "search_by_concept",
        "tests/ontology_classification_e2e.rs",
        "Fixed ontology hierarchy and classification target.",
        "concept_count",
    ),
    D::active(
        K::Node,
        "Context",
        "tooling_manager/add_pipeline",
        "add_pipeline::context_link",
        "getMemoryContexts",
        GRAPH_E2E,
        "Situational validity boundary for memories.",
        "context_count",
    ),
    D::reserved(
        K::Node,
        "Constraint",
        "core/charter",
        RESERVED_MILESTONE,
        "Reserved persisted constraint shape; the live charter is code and memory-charter.md.",
        "constraint_count",
    ),
    D::deprecated(
        K::Node,
        "Reasoning",
        "mind_toolbox/reasoning",
        "Keep the declaration read-only, prove reasoning_count=0, take a verified cold volume backup, run helix check with v2.3.5, then remove it only in a dedicated compatible schema migration; first-class Memory edges remain authoritative.",
        "Deprecated duplicate of the live first-class reasoning-edge model.",
        "reasoning_count",
    ),
    D::active(
        K::Node,
        "HistoryEvent",
        "tooling_manager/add_pipeline",
        "ToolingManager::add_memory_history_event",
        "getMemoryHistory",
        "tests/supersede_demotion_e2e.rs",
        "Append-only memory decision audit trail.",
        "history_event_count",
    ),
    D::active(
        K::Node,
        "MemoryChunk",
        "mind_toolbox/chunking",
        "ChunkingManager::store_chunks",
        "getMemoryChunks",
        "tests/chunking_e2e.rs",
        "Oversized raw-source reconstruction chunk.",
        "memory_chunk_count",
    ),
    D::reserved(
        K::Node,
        "DocPage",
        "reserved/document-ingest",
        RESERVED_MILESTONE,
        "Reserved documentation-ingest page.",
        "doc_page_count",
    ),
    D::reserved(
        K::Node,
        "DocChunk",
        "reserved/document-ingest",
        RESERVED_MILESTONE,
        "Reserved documentation-ingest chunk; distinct from MemoryChunk.",
        "doc_chunk_count",
    ),
    D::reserved(
        K::Node,
        "CodeExample",
        "reserved/document-ingest",
        RESERVED_MILESTONE,
        "Reserved structured code example.",
        "code_example_count",
    ),
    D::reserved(
        K::Node,
        "ErrorCode",
        "reserved/document-ingest",
        RESERVED_MILESTONE,
        "Reserved structured error-code reference.",
        "error_code_count",
    ),
    D::active(
        K::Node,
        "PendingInput",
        "tooling_manager/ingest",
        "IngestBuffer::enqueue",
        "IngestBuffer::worker",
        BUFFER_E2E,
        "Transient durable write queue.",
        "pending_input_count",
    ),
    D::active(
        K::Node,
        "MemoryNotice",
        "tooling_manager/ingest",
        "IngestBuffer::store_notice",
        "ToolingManager::pending_outcomes",
        BUFFER_E2E,
        "Deferred write outcome delivered to its owner.",
        "memory_notice_count",
    ),
    D::active(
        K::Node,
        "Category",
        "agents/clotho",
        "ToolingManager::ensure_category",
        "Lachesis category routing",
        MOIRAI_E2E,
        "Controlled vocabulary and Moirai routing substrate.",
        "category_count",
    ),
];

pub const VECTORS: &[D] = &[
    D::active(
        K::Vector,
        "MemoryEmbedding",
        "mind_toolbox/memory",
        "addMemoryEmbedding",
        "smartVectorSearch",
        "tests/read_path_e2e.rs",
        "Primary vector index for hybrid retrieval.",
        "memory_embedding_count",
    ),
    D::reserved(
        K::Vector,
        "EntityEmbedding",
        "mind_toolbox/entity",
        RESERVED_MILESTONE,
        "Reserved persisted entity-resolution index.",
        "entity_embedding_count",
    ),
    D::reserved(
        K::Vector,
        "ChunkEmbedding",
        "reserved/document-ingest",
        RESERVED_MILESTONE,
        "Reserved vector index for inactive DocChunk ingestion.",
        "chunk_embedding_count",
    ),
    D::reserved(
        K::Vector,
        "ConceptEmbedding",
        "mind_toolbox/ontology",
        RESERVED_MILESTONE,
        "Reserved vector index; fixed ontology lookup is authoritative.",
        "concept_embedding_count",
    ),
    D::reserved(
        K::Vector,
        "CategoryEmbedding",
        "agents/clotho",
        RESERVED_MILESTONE,
        "Reserved vector index; Clotho currently computes cosine in process.",
        "category_embedding_count",
    ),
];
