//! MCP tool surface for [`super::HelixirMcpServer`].
//!
//! The tool surface is split by domain so each file stays small and
//! cohesive. Every submodule defines its own `#[tool_router(router = ...)]`
//! block, which `rmcp` compiles into a public router constructor. We then
//! combine those routers via the `+` operator in
//! [`HelixirMcpServer::build_tool_router`].
//!
//! - `memory_*` — long-term memory split into write, read, swarm, and graph domains.
//! - [`think`] — FastThink ephemeral working-memory sessions.

use super::server::HelixirMcpServer;

mod memory_graph;
mod memory_read;
mod memory_support;
mod memory_swarm;
mod memory_write;
mod think;

impl HelixirMcpServer {
    /// Build the full `ToolRouter` by merging per-domain routers.
    ///
    /// Each subrouter is generated by `rmcp::tool_router` and exposed with
    /// `vis = "pub(super)"` from its module. The `+` operator on
    /// `ToolRouter<Self>` merges entries into a single router.
    pub(super) fn build_tool_router() -> rmcp::handler::server::router::tool::ToolRouter<Self> {
        Self::memory_write_router()
            + Self::memory_read_router()
            + Self::memory_swarm_router()
            + Self::memory_graph_router()
            + Self::think_router()
    }
}
